name: example
description: Example of usage of google_my_business package
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_my_business:
    path: ../

flutter:
  uses-material-design: true