name: google_my_business
description:
  Flutter package to work with Google My Business API.
  Simplifies communication & interaction with GMB API endpoints.
version: 0.3.3
homepage: https://github.com/Newgarden-Solutions/google_my_business
repository: https://github.com/Newgarden-Solutions/google_my_business
issue_tracker: https://github.com/Newgarden-Solutions/google_my_business/issues

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Google
  google_sign_in: ^6.1.4
  google_sign_in_platform_interface: ^2.4.1

  # Util
  http: ^1.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5

  json_serializable: ^6.7.0

  # Tests
  mockito: ^5.4.2

false_secrets:
  - example/ios/Runner/GoogleService-Info.plist
