name: google_my_business
description:
  Flutter package to work with Google My Business API.
  Simplifies communication & interaction with GMB API endpoints.
version: 0.3.1
homepage: https://github.com/Newgarden-Solutions/google_my_business
repository: https://github.com/Newgarden-Solutions/google_my_business
issue_tracker: https://github.com/Newgarden-Solutions/google_my_business/issues

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Google
  google_sign_in: 5.2.1
  google_sign_in_platform_interface: 2.1.0

  # Util
  http: 0.13.4
  json_annotation: 4.4.0

  # Tests
  mockito: 5.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.1.7
  json_serializable: 6.1.3
