name: google_my_business
description:
  Flutter package to work with Google My Business API.
  Simplifies communication & interaction with GMB API endpoints.
version: 0.2.1
homepage: https://github.com/Newgarden-Solutions/google_my_business
repository: https://github.com/Newgarden-Solutions/google_my_business
issue_tracker: https://github.com/Newgarden-Solutions/google_my_business/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Google
  google_sign_in: ^4.5.9

  # Util
  http: ^0.12.2

  # Tests
  mockito: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
