name: google_my_business
description:
  Flutter package to work with Google My Business API.
  Simplifies communication & interaction with GMB API endpoints.
version: 0.3.0
homepage: https://github.com/Newgarden-Solutions/google_my_business
repository: https://github.com/Newgarden-Solutions/google_my_business
issue_tracker: https://github.com/Newgarden-Solutions/google_my_business/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

  # Google
  google_sign_in: ^5.0.1

  # Util
  http: ^0.13.1
  json_annotation: ^4.0.1

  # Tests
  mockito: ^5.0.3

dev_dependencies:
  test: ^1.16.8
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
