name: build

on:
  push:
    branches: [ master, release/* ]
  pull_request:
    branches: [ master, release/* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.0'

      - name: Print Flutter & Dart SDK version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze

      - name: Run tests and generate coverage
        run: |
          sudo apt-get update -qq -y
          sudo apt-get install lcov -y
          flutter test --coverage
          flutter pub global activate remove_from_coverage
          remove_from_coverage -f coverage/lcov.info -r '.g.dart$'
          genhtml coverage/lcov.info --output=coverage
          bash <(curl -s https://codecov.io/bash)
